#FROM ubuntu:xenial
FROM ubuntu:trusty
#FROM x3193/dc:latest
#FROM x3193/ubt1404:latest
MAINTAINER x3193.tk <x3193@x3193.tk> 
 
ENV DEBIAN_FRONTEND noninteractive
ENV HOME /root
ENV USER root
ENV AUTHORIZED_KEYS **None**
ENV ROOT_PASS EUIfgwe7

ENV APACHE_RUN_USER ops
ENV APACHE_RUN_GROUP root
#ENV APACHE_RUN_USER www-data
#ENV APACHE_RUN_GROUP www-data
ENV APACHE_PID_FILE /var/run/apache2/apache2.pid
ENV APACHE_RUN_DIR /var/run/apache2
ENV APACHE_LOCK_DIR /var/lock/apache2
# Only /var/log/apache2 is handled by /etc/logrotate.d/apache2.
ENV APACHE_LOG_DIR /var/log/apache2

# Install packages
RUN dpkg --configure -a && apt-get install -f && apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -y install expect sudo openssh-server python-numpy python3-numpy
#RUN dpkg --configure -a && apt-get install -f && apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -y install sudo net-tools openssh-server pwgen zip unzip python-numpy python3-numpy cron
RUN mkdir -p /var/run/sshd && sed -i "s/UsePrivilegeSeparation.*/UsePrivilegeSeparation no/g" /etc/ssh/sshd_config && sed -i "s/UsePAM.*/UsePAM no/g" /etc/ssh/sshd_config && sed -i "s/PermitRootLogin.*/PermitRootLogin yes/g" /etc/ssh/sshd_config

ADD set_root_pw.sh /set_root_pw.sh
ADD run.sh /run.sh
ADD exp.sh /exp.sh
ADD runexp.sh /runexp.sh
RUN chmod +x /*.sh

#RUN whereis exec
RUN sh /set_root_pw.sh
#RUN whereis expect
RUN sudo DEBIAN_FRONTEND=noninteractive apt-get install -y zip unzip git wget vim supervisor git apache2 libapache2-mod-php5 mysql-server php5-mysql pwgen php-apc php5-mcrypt php5-gd php5-curl php5-dev phpmyadmin apache2-mpm-* -y  
RUN service apache2 restart
RUN sudo php5enmod opcache
RUN sudo php5enmod mcrypt
RUN echo "ServerName localhost" >> /etc/apache2/apache2.conf
RUN sudo a2enmod rewrite
RUN sed -i "s/Listen 80*/Listen 8080/g" /etc/apache2/ports.conf
RUN sed -i "s/<VirtualHost \*\:80>/<VirtualHost \*\:8080>/g" /etc/apache2/sites-available/000-default.conf
RUN cat /etc/apache2/ports.conf
RUN cat /etc/apache2/sites-available/000-default.conf
RUN chown -R root:root /var/log/apache2
RUN chmod -R 7777 /var/log/apache2
RUN service apache2 restart

EXPOSE 22
EXPOSE 80
EXPOSE 6080
EXPOSE 5901
EXPOSE 5902
EXPOSE 8080

WORKDIR /root

RUN adduser --shell /bin/bash --system --ingroup root --force-badname --uid 1001 ops
#RUN echo "ops:EUIfgwe7" | chpasswd
RUN echo "ops ALL=(ALL:ALL) NOPASSWD: ALL" >> /etc/sudoers
#RUN echo "ops ALL=(ALL:ALL) NOPASSWD: ALL" >> /etc/sudoers
RUN echo "Defaults visiblepw" >> /etc/sudoers
#RUN sed -i "s/# auth       sufficient pam_wheel.so trust/auth       sufficient pam_wheel.so trust/g" /etc/pam.d/su
RUN usermod -a -G sudo ops
RUN usermod -a -G adm ops

#RUN adduser --shell /bin/bash --system --ingroup root --force-badname --uid 1005790000 x3193
#RUN echo "x3193 ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
#RUN usermod -a -G sudo x3193
#RUN usermod -a -G adm x3193
#RUN adduser --shell /bin/bash --lastuid 1005790000 --system --ingroup root --uid 1005790000 x3193
RUN echo "1007870000 ALL=(ALL:ALL) NOPASSWD: ALL" >> /etc/sudoers
#RUN chown -R 1007870000:root /etc/init.d/ssh
#RUN chmod -R 0700 /etc/init.d/ssh
#RUN chown -R 1007870000:root /etc/ssh/
#RUN chmod -R 0700 /etc/ssh/
#RUN adduser --shell /bin/bash --system --ingroup root --force-badname www-data
RUN usermod -a -G root www-data
RUN usermod -a -G sudo www-data
RUN usermod -a -G adm www-data
RUN echo "www-data ALL=(ALL:ALL) NOPASSWD: ALL" >> /etc/sudoers

USER 1001
#USER 0
#USER 1005790000

#CMD exec apache2 -D FOREGROUND
CMD exec apache2 -D FOREGROUND
#CMD echo "2222222"
#ENTRYPOINT ["/run.sh", "-D", "FOREGROUND"]
#ENTRYPOINT ["/run.sh", "-D", "FOREGROUND"]
#CMD sh /runexp.sh
#CMD ["sudo","sh","/run.sh"]
#CMD ["/exp.sh"]
#CMD ["/run.sh", "-D", "FOREGROUND"]
