#!/bin/bash

echo "---------------------update-----------------------"  ;
sudo dpkg --configure -a ;
sudo apt-get dist-upgrade -y ;
sudo apt-get update -y ;
sudo apt-get upgrade -y ;
echo "---------------------------php-----------------"  ;
#sudo DEBIAN_FRONTEND=noninteractive apt-get build-dep -y --force-yes --no-install-recommends  firefox putty htop unrar-free zip unzip git wget vim supervisor git apache2 libapache2-mod-php5 mysql-server php5-mysql pwgen php-apc php5-mcrypt php5-gd php5-curl php5-xdebug phpmyadmin -y  ;
sudo DEBIAN_FRONTEND=noninteractive apt-get install -y --force-yes --no-install-recommends zip unzip git wget vim supervisor git apache2 libapache2-mod-php5 mysql-server php5-mysql pwgen php-apc php5-mcrypt php5-gd php5-curl php5-xdebug phpmyadmin -y  ;
sudo service apache2 restart  ;
sudo service mysql restart  ;
sudo php5enmod mcrypt ;
echo "ServerName localhost" >> /etc/apache2/apache2.conf ;
chmod -R 7777 /var/www/html ;
sudo a2enmod rewrite ;
sudo /etc/init.d/apache2 restart  ;
echo "---------------------filemanager-----------------------"  ;
sudo chmod -R 7777 /var/www/html ;
sudo find /var/www/html -name index.html -delete ;
cd /var/www/html/opensource/ald ;
sudo cp -f .htaccess filebox.php diy.php /var/www/html ;
sudo cp -f 000-default.conf /etc/apache2/sites-available  ;
sudo service apache2 restart  ;
sudo cp -f /var/www/html/filebox.php /var/www/html/index.php ;
echo "--------------------DNS------------------------"  ;
cd /var/www/html/opensource/ald ;
sudo mkdir -vp /var/www/html/dz32;
sudo chmod -R 7777 /var/www/html/dz32;
sudo cp -f *.conf /etc/apache2/sites-available  ;
cd /
sudo find /etc/apache2/sites-available/ -name '*.conf' -exec sudo ln -s {} /etc/apache2/sites-enabled/  \;  ;
sudo service apache2 restart  ;
echo "--------------------mysql------------------------"  ;
cd /var/www/html/opensource/ald ;
sudo cp -f my.cnf /var/lib/mysql ;
sudo service mysql restart  ;
sudo /usr/bin/mysqladmin -u root password 'EUIfgwe7' ;
sudo service mysql restart  ;
echo "--------------------phpmyadmin-----------------------"  ;
cd /var/www/html;
sudo ln -s /usr/share/phpmyadmin phpmyadmin ;
sudo chmod -R 7777 /usr/share/phpmyadmin ;
cd /var/www/html/opensource/ald ;
sudo cp -f Config.class.php /usr/share/phpmyadmin/libraries ;
sudo cp -f diy.php /usr/share/phpmyadmin ;
sudo php5enmod mcrypt;
sudo service apache2 restart ;
sudo service mysql restart ;
echo "---------------------crontab-----------------------"  ;
cd /var/www/html/opensource/ald ;
sudo cp -f crontab /etc ;
sudo cp -f cron_hourly.sh /etc/cron.hourly ;
sudo cp -f cron_daily.sh /etc/cron.daily ;
sudo /etc/init.d/cron restart ;
sudo cron  ;
sudo /etc/init.d/cron restart ;
echo "------------------------soft--------------------"  ;
sudo DEBIAN_FRONTEND=noninteractive apt-get install -y --force-yes --no-install-recommends firefox firefox-locale-zh-hant dosbox putty visualboyadvance visualboyadvance-gtk libreoffice libreoffice-l10n-zh-cn;
echo "------------------------Clean--------------------"  ;
sudo apt-get autoremove -y  ;
sudo apt-get clean -y  ;
sudo apt-get autoclean -y  ;
echo "--------------------------------------------"  ;